#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7FD9FCCB000BEEEE (meyering@fb.com)
#
Name     : gzip
Version  : 1.12
Release  : 32
URL      : https://mirrors.kernel.org/gnu/gzip/gzip-1.12.tar.xz
Source0  : https://mirrors.kernel.org/gnu/gzip/gzip-1.12.tar.xz
Source1  : https://mirrors.kernel.org/gnu/gzip/gzip-1.12.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3+ GPL-3.0 GPL-3.0+
Requires: gzip-bin = %{version}-%{release}
Requires: gzip-info = %{version}-%{release}
Requires: gzip-license = %{version}-%{release}
Requires: gzip-man = %{version}-%{release}
BuildRequires : grep
BuildRequires : less
BuildRequires : util-linux

%description
The GNU gzip home page is https://www.gnu.org/software/gzip.
gzip (GNU zip) is a compression utility designed to be a replacement
for 'compress'. Its main advantages over compress are much better
compression and freedom from patented algorithms.  The GNU Project
uses it as the standard compression program for its system.

%package bin
Summary: bin components for the gzip package.
Group: Binaries
Requires: gzip-license = %{version}-%{release}

%description bin
bin components for the gzip package.


%package info
Summary: info components for the gzip package.
Group: Default

%description info
info components for the gzip package.


%package license
Summary: license components for the gzip package.
Group: Default

%description license
license components for the gzip package.


%package man
Summary: man components for the gzip package.
Group: Default

%description man
man components for the gzip package.


%prep
%setup -q -n gzip-1.12
cd %{_builddir}/gzip-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649374167
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mno-vzeroupper -mprefer-vector-width=256 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1649374167
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gzip
cp %{_builddir}/gzip-1.12/COPYING %{buildroot}/usr/share/package-licenses/gzip/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/gzip

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gunzip
/usr/bin/gzexe
/usr/bin/uncompress
/usr/bin/zcat
/usr/bin/zcmp
/usr/bin/zdiff
/usr/bin/zegrep
/usr/bin/zfgrep
/usr/bin/zforce
/usr/bin/zgrep
/usr/bin/zless
/usr/bin/zmore
/usr/bin/znew

%files info
%defattr(0644,root,root,0755)
/usr/share/info/gzip.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gzip/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/gunzip.1
/usr/share/man/man1/gzexe.1
/usr/share/man/man1/gzip.1
/usr/share/man/man1/zcat.1
/usr/share/man/man1/zcmp.1
/usr/share/man/man1/zdiff.1
/usr/share/man/man1/zforce.1
/usr/share/man/man1/zgrep.1
/usr/share/man/man1/zless.1
/usr/share/man/man1/zmore.1
/usr/share/man/man1/znew.1
